title: Tarryn Bourhill
description: Articles and information about science for everyone
url: https://tbourhill.com
logo: /assets/images/site_logo.png
social:
  name: Tarryn Bourhill
  links:
    - https://www.linkedin.com/in/tarrynbourhill

google_verification: kmFOoT0AIUay3KoYHSnij5ov353H0AOu8RdnJAneTrU

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/**/*.png"
    values:
      sitemap: false
  - scope:
      path: "assets/**/*.jpg"
    values:
      sitemap: false
  - scope:
      path: "assets/**/*.jpeg"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
